# Generated by Django 4.0.4 on 2022-05-26 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=20)),
                ('model', models.CharField(max_length=40)),
                ('description', models.TextField()),
                ('publish_date', models.DateField()),
                ('size', models.CharField(choices=[('39', '39')], max_length=2)),
            ],
        ),
    ]
