# Generated by Django 4.0.4 on 2022-05-26 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes_app', '0002_alter_shoes_size'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shoes',
            options={'verbose_name_plural': 'Shoes'},
        ),
        migrations.RemoveField(
            model_name='shoes',
            name='publish_date',
        ),
        migrations.AddField(
            model_name='shoes',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Unisex', 'Unisex')], default='Unisex', max_length=10),
        ),
        migrations.AddField(
            model_name='shoes',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='shoes',
            name='premier_date',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='shoes',
            name='price',
            field=models.DecimalField(decimal_places=2, default=800, max_digits=6),
        ),
        migrations.AddField(
            model_name='shoes',
            name='quantity',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
